spring.application.name=hospital-management

server.port=${PORT:8080}

# ==============================
# DATABASE
# ==============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hospital_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ==============================
# JPA
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ==============================
# JWT
# ==============================

jwt.secret=${JWT_SECRET:hospital-management-secret-key-change-this-in-production}
jwt.expiration=${JWT_EXPIRATION:3600000}